#!/usr/bin/env node
/*
 * Extracts the clinical content (patients, episodes, critical lab rounds,
 * pager events, lab database) from the legacy single-file app
 * (game/library/index.html) into game/js/content.js.
 *
 * Usage: node tools/extract-content.js [legacy.html] [out.js]
 * Only object/array literals are evaluated (in an empty VM context); the
 * legacy app's runtime code is never executed.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const src = process.argv[2] || path.join(root, 'game/library/index.html');
const out = process.argv[3] || path.join(root, 'game/js/content.js');
const html = fs.readFileSync(src, 'utf8');
const scripts = [...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);

// Returns the literal assigned to `const NAME=` in the first script that defines it.
// `marker` disambiguates names that appear in more than one script.
function literal(name, marker) {
  const re = new RegExp('const\\s+' + name + '\\s*=\\s*([\\[{])');
  for (const s of scripts) {
    if (marker && !s.includes(marker)) continue;
    const m = re.exec(s);
    if (!m) continue;
    const start = m.index + m[0].length - 1;
    const open = s[start], close = open === '[' ? ']' : '}';
    let depth = 0, quote = null;
    for (let j = start; j < s.length; j++) {
      const c = s[j];
      if (quote) { if (c === '\\') { j++; continue; } if (c === quote) quote = null; continue; }
      if (c === '"' || c === "'" || c === '`') { quote = c; continue; }
      if (c === '/' && s[j + 1] === '/') { j = s.indexOf('\n', j); continue; }
      if (c === open) depth++;
      else if (c === close && --depth === 0) return vm.runInNewContext('(' + s.slice(start, j + 1) + ')', {});
    }
  }
  throw new Error('literal not found: ' + name);
}

const content = {
  patients: literal('P', "clinicalMasteryRpgV16"),
  episodes: literal('E', "clinicalMasteryRpgV16"),
  labRounds: literal('cases', 'v21RoundCounter'),
  events: literal('events', 'clinicalMasteryPersonalRpgV13'),
  labs: literal('labData'),
};

// Sanity checks: every correct-answer index must point at an existing option.
const bad = [];
for (const e of content.episodes) {
  for (const [k, kc] of [['q', 'qc'], ['g', 'gc'], ['x', 'xc'], ['r', 'rc']]) {
    if (!(e[kc] >= 0 && e[kc] < e[k].length)) bad.push(`${e.id}.${kc}`);
  }
  if (!content.patients[e.p]) bad.push(`${e.id}.p`);
}
content.labRounds.forEach((c, i) => c.steps.forEach((s, j) => { if (!(s[2] >= 0 && s[2] < s[1].length)) bad.push(`round${i}.${j}`); }));
content.events.forEach((e, i) => { if (!(e.c >= 0 && e.c < e.a.length)) bad.push(`event${i}`); });
if (bad.length) { console.error('Invalid answer keys:', bad.join(', ')); process.exit(1); }

fs.writeFileSync(out, '/* Generated by tools/extract-content.js — do not edit by hand. */\nwindow.CONTENT=' + JSON.stringify(content) + ';\n');
console.log(Object.entries(content).map(([k, v]) => `${k}: ${Array.isArray(v) ? v.length : Object.keys(v).length}`).join(', '), '→', path.relative(root, out));
