/* המשמרת — the evidence layer.
   Every clinical encounter is tied to the guideline/review it is built on, plus one concrete,
   guideline-derived "key point". Links go to PubMed searches or the publisher's official page.
   The pedagogy section documents why the game mechanics look the way they do. */
'use strict';

const pm = q => 'https://pubmed.ncbi.nlm.nih.gov/?term=' + encodeURIComponent(q);

const SOURCES = {
  // geriatrics & prescribing
  beers2023: { t: 'AGS Beers Criteria® 2023', c: 'American Geriatrics Society Beers Criteria Update Expert Panel. J Am Geriatr Soc 2023;71(7):2052–2081.', u: pm('American Geriatrics Society 2023 updated AGS Beers Criteria') },
  stopp2023: { t: 'STOPP/START v3 (2023)', c: "O'Mahony D, et al. STOPP/START criteria for potentially inappropriate prescribing in older people: version 3. Eur Geriatr Med 2023;14:625–632.", u: pm('STOPP/START criteria version 3 O\'Mahony 2023') },
  scott2015: { t: 'Deprescribing process (2015)', c: 'Scott IA, et al. Reducing inappropriate polypharmacy: the process of deprescribing. JAMA Intern Med 2015;175(5):827–834.', u: pm('Reducing inappropriate polypharmacy: the process of deprescribing') },
  falls2022: { t: 'World Falls Guidelines (2022)', c: 'Montero-Odasso M, et al. World guidelines for falls prevention and management for older adults. Age Ageing 2022;51(9):afac205.', u: pm('World guidelines for falls prevention and management for older adults Montero-Odasso') },
  freeman2011: { t: 'Orthostatic hypotension consensus (2011)', c: 'Freeman R, et al. Consensus statement on the definition of orthostatic hypotension. Clin Auton Res 2011;21:69–72.', u: pm('Consensus statement on the definition of orthostatic hypotension neurally mediated syncope Freeman 2011') },
  nice_delirium: { t: 'NICE CG103 Delirium', c: 'NICE. Delirium: prevention, diagnosis and management in hospital and long-term care (CG103, updated 2023).', u: 'https://www.nice.org.uk/guidance/cg103' },
  tieges2021: { t: '4AT meta-analysis (2021)', c: 'Tieges Z, et al. Diagnostic accuracy of the 4AT for delirium detection in older adults: systematic review and meta-analysis. Age Ageing 2021;50(3):733–743.', u: pm('Diagnostic accuracy of the 4AT for delirium detection in older adults') },
  inouye1999: { t: 'HELP — delirium prevention (1999)', c: 'Inouye SK, et al. A multicomponent intervention to prevent delirium in hospitalized older patients. N Engl J Med 1999;340:669–676.', u: pm('A multicomponent intervention to prevent delirium in hospitalized older patients') },
  npiap2019: { t: 'EPUAP/NPIAP/PPPIA 2019', c: 'EPUAP/NPIAP/PPPIA. Prevention and Treatment of Pressure Ulcers/Injuries: Clinical Practice Guideline. The International Guideline, 2019.', u: 'https://internationalguideline.com/' },
  nice_cg124: { t: 'NICE CG124 Hip fracture', c: 'NICE. Hip fracture: management (CG124, updated 2023).', u: 'https://www.nice.org.uk/guidance/cg124' },
  nice_ng27: { t: 'NICE NG27 Transitions of care', c: 'NICE. Transition between inpatient hospital settings and community or care home settings for adults with social care needs (NG27).', u: 'https://www.nice.org.uk/guidance/ng27' },
  who_toc2019: { t: 'WHO — Medication safety in transitions of care', c: 'World Health Organization. Medication Safety in Transitions of Care. Geneva: WHO; 2019.', u: 'https://www.who.int/publications/i/item/WHO-UHC-SDS-2019.9' },
  ahrq_teachback: { t: 'AHRQ Teach-Back', c: 'AHRQ Health Literacy Universal Precautions Toolkit, Tool 5: Use the Teach-Back Method.', u: 'https://www.ahrq.gov/health-literacy/improve/precautions/tool5.html' },
  // neuro
  aha_stroke2019: { t: 'AHA/ASA Acute Ischemic Stroke 2019', c: 'Powers WJ, et al. Guidelines for the early management of patients with acute ischemic stroke: 2019 update. Stroke 2019;50:e344–e418.', u: pm('Guidelines for the Early Management of Patients With Acute Ischemic Stroke: 2019 Update') },
  trinka2015: { t: 'ILAE status epilepticus definition (2015)', c: 'Trinka E, et al. A definition and classification of status epilepticus — Report of the ILAE Task Force. Epilepsia 2015;56(10):1515–1523.', u: pm('A definition and classification of status epilepticus Report of the ILAE Task Force') },
  nice_ng232: { t: 'NICE NG232 Head injury (2023)', c: 'NICE. Head injury: assessment and early management (NG232, 2023).', u: 'https://www.nice.org.uk/guidance/ng232' },
  // cardio-respiratory
  acls2020: { t: 'AHA 2020 Adult ALS', c: 'Panchal AR, et al. Part 3: Adult Basic and Advanced Life Support. 2020 AHA Guidelines for CPR and ECC. Circulation 2020;142(16 Suppl 2):S366–S468.', u: pm('Part 3: Adult Basic and Advanced Life Support 2020 American Heart Association Guidelines') },
  af2023: { t: 'ACC/AHA/ACCP/HRS AF 2023', c: 'Joglar JA, et al. 2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation. Circulation 2024;149:e1–e156.', u: pm('2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation') },
  hf2022: { t: 'AHA/ACC/HFSA Heart Failure 2022', c: 'Heidenreich PA, et al. 2022 AHA/ACC/HFSA Guideline for the Management of Heart Failure. Circulation 2022;145:e895–e1032.', u: pm('2022 AHA/ACC/HFSA Guideline for the Management of Heart Failure') },
  esc_htn2024: { t: 'ESC Hypertension 2024', c: 'McEvoy JW, et al. 2024 ESC Guidelines for the management of elevated blood pressure and hypertension. Eur Heart J 2024;45:3912–4018.', u: pm('2024 ESC Guidelines for the management of elevated blood pressure and hypertension') },
  thygesen2018: { t: 'Fourth Universal Definition of MI', c: 'Thygesen K, et al. Fourth Universal Definition of Myocardial Infarction (2018). Circulation 2018;138:e618–e651.', u: pm('Fourth Universal Definition of Myocardial Infarction (2018)') },
  esc_pe2019: { t: 'ESC Pulmonary Embolism 2019', c: 'Konstantinides SV, et al. 2019 ESC Guidelines for the diagnosis and management of acute pulmonary embolism. Eur Heart J 2020;41:543–603.', u: pm('2019 ESC Guidelines for the diagnosis and management of acute pulmonary embolism') },
  righini2014: { t: 'ADJUST-PE: age-adjusted D-dimer', c: 'Righini M, et al. Age-adjusted D-dimer cutoff levels to rule out pulmonary embolism: the ADJUST-PE study. JAMA 2014;311(11):1117–1124.', u: pm('Age-adjusted D-dimer cutoff levels to rule out pulmonary embolism ADJUST-PE') },
  drew2010: { t: 'AHA — Torsade prevention in hospital', c: 'Drew BJ, et al. Prevention of torsade de pointes in hospital settings: a scientific statement from the AHA and ACCF. Circulation 2010;121:1047–1060.', u: pm('Prevention of torsade de pointes in hospital settings scientific statement') },
  gold2025: { t: 'GOLD 2025 Report', c: 'Global Initiative for Chronic Obstructive Lung Disease. Global Strategy for Prevention, Diagnosis and Management of COPD: 2025 Report.', u: 'https://goldcopd.org/' },
  bts_o2_2017: { t: 'BTS Emergency Oxygen 2017', c: "O'Driscoll BR, et al. BTS guideline for oxygen use in adults in healthcare and emergency settings. Thorax 2017;72(Suppl 1):ii1–ii90.", u: pm('BTS guideline for oxygen use in adults in healthcare and emergency settings') },
  mandell2019: { t: 'Aspiration pneumonia (NEJM 2019)', c: 'Mandell LA, Niederman MS. Aspiration Pneumonia. N Engl J Med 2019;380:651–663.', u: pm('Mandell Niederman Aspiration Pneumonia N Engl J Med 2019') },
  // renal / metabolic
  ukka_k: { t: 'UKKA Hyperkalaemia guideline', c: 'UK Kidney Association. Clinical Practice Guideline: Management of Hyperkalaemia in Adults (2020; updated 2023 and 2026).', u: 'https://www.ukkidney.org/health-professionals/guidelines/guidelines-commentaries' },
  kdigo_aki2012: { t: 'KDIGO AKI 2012', c: 'KDIGO Clinical Practice Guideline for Acute Kidney Injury. Kidney Int Suppl 2012;2:1–138.', u: 'https://kdigo.org/guidelines/acute-kidney-injury/' },
  kdigo_ckd2024: { t: 'KDIGO CKD 2024', c: 'KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of CKD. Kidney Int 2024;105(4S):S117–S314.', u: 'https://kdigo.org/guidelines/ckd-evaluation-and-management/' },
  kdigo_anemia2026: { t: 'KDIGO Anemia in CKD 2026', c: 'KDIGO 2026 Clinical Practice Guideline for the Management of Anemia in CKD (update of the 2012 guideline).', u: 'https://kdigo.org/guidelines/anemia-in-ckd/' },
  spasovski2014: { t: 'European hyponatraemia guideline 2014', c: 'Spasovski G, et al. Clinical practice guideline on diagnosis and treatment of hyponatraemia. Eur J Endocrinol 2014;170(3):G1–G47.', u: pm('Clinical practice guideline on diagnosis and treatment of hyponatraemia Spasovski') },
  adrogue2000: { t: 'Hypernatremia (NEJM 2000)', c: 'Adrogué HJ, Madias NE. Hypernatremia. N Engl J Med 2000;342:1493–1499.', u: pm('Adrogue Madias Hypernatremia N Engl J Med 2000') },
  ada2025: { t: 'ADA Standards of Care 2025 — Older Adults', c: 'American Diabetes Association. 13. Older Adults: Standards of Care in Diabetes—2025. Diabetes Care 2025;48(Suppl 1).', u: pm('Older Adults: Standards of Care in Diabetes-2025') },
  umpierrez2024: { t: 'Hyperglycemic crises consensus 2024', c: 'Umpierrez GE, et al. Hyperglycemic crises in adults with diabetes: a consensus report (ADA/EASD/JBDS/AACE/DTS). Diabetes Care 2024;47(8):1257–1275.', u: pm('Hyperglycemic crises in adults with diabetes: a consensus report 2024') },
  berend2014: { t: 'Acid–base: physiological approach (NEJM 2014)', c: 'Berend K, de Vries APJ, Gans ROB. Physiological approach to assessment of acid–base disturbances. N Engl J Med 2014;371:1434–1445.', u: pm('Physiological approach to assessment of acid-base disturbances Berend') },
  nice_cg32: { t: 'NICE CG32 Nutrition support', c: 'NICE. Nutrition support for adults: oral nutrition support, enteral tube feeding and parenteral nutrition (CG32).', u: 'https://www.nice.org.uk/guidance/cg32' },
  endo_ca2023: { t: 'Endocrine Society — Hypercalcemia of malignancy 2023', c: 'El-Hajj Fuleihan G, et al. Treatment of hypercalcemia of malignancy in adults: an Endocrine Society clinical practice guideline. J Clin Endocrinol Metab 2023;108(3):507–528.', u: pm('Treatment of Hypercalcemia of Malignancy in Adults Endocrine Society Clinical Practice Guideline') },
  // infection / hematology
  ssc2021: { t: 'Surviving Sepsis Campaign 2021', c: 'Evans L, et al. Surviving Sepsis Campaign: international guidelines for management of sepsis and septic shock 2021. Crit Care Med 2021;49(11):e1063–e1143.', u: pm('Surviving sepsis campaign: international guidelines for management of sepsis and septic shock 2021') },
  sepsis3: { t: 'Sepsis-3 (2016)', c: 'Singer M, et al. The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3). JAMA 2016;315(8):801–810.', u: pm('The Third International Consensus Definitions for Sepsis and Septic Shock') },
  taylor2001: { t: 'ISTH overt DIC score', c: 'Taylor FB Jr, et al. Towards definition, clinical and laboratory criteria, and a scoring system for disseminated intravascular coagulation. Thromb Haemost 2001;86:1327–1330.', u: pm('Towards definition, clinical and laboratory criteria, and a scoring system for disseminated intravascular coagulation') },
  idsa_cdi2021: { t: 'IDSA/SHEA C. difficile 2021', c: 'Johnson S, et al. Clinical Practice Guideline by IDSA and SHEA: 2021 Focused Update on Management of Clostridioides difficile Infection in Adults. Clin Infect Dis 2021;73(5):e1029–e1044.', u: pm('2021 Focused Update Guidelines on Management of Clostridioides difficile Infection in Adults') },
  freifeld2011: { t: 'IDSA Febrile neutropenia', c: 'Freifeld AG, et al. Clinical practice guideline for the use of antimicrobial agents in neutropenic patients with cancer: 2010 update by IDSA. Clin Infect Dis 2011;52(4):e56–e93.', u: pm('Clinical practice guideline for the use of antimicrobial agents in neutropenic patients with cancer 2010 update') },
  mermel2009: { t: 'IDSA Catheter-related BSI', c: 'Mermel LA, et al. Clinical practice guidelines for the diagnosis and management of intravascular catheter-related infection: 2009 update by IDSA. Clin Infect Dis 2009;49:1–45.', u: pm('Clinical practice guidelines for the diagnosis and management of intravascular catheter-related infection 2009') },
  aabb2023: { t: 'AABB RBC Transfusion 2023', c: 'Carson JL, et al. Red Blood Cell Transfusion: 2023 AABB International Guidelines. JAMA 2023;330(19):1892–1902.', u: pm('Red Blood Cell Transfusion: 2023 AABB International Guidelines') },
  bsh_atr2023: { t: 'BSH Acute transfusion reactions 2023', c: 'Soutar R, et al. Guideline on the investigation and management of acute transfusion reactions. Br J Haematol 2023;201:832–844.', u: 'https://b-s-h.org.uk/guidelines/guidelines/guideline-on-the-investigation-and-management-of-acute-transfusion-reactions' },
  aga2020: { t: 'AGA Iron-deficiency anemia 2020', c: 'Ko CW, et al. AGA Clinical Practice Guidelines on the Gastrointestinal Evaluation of Iron Deficiency Anemia. Gastroenterology 2020;159:1085–1094.', u: 'https://gastro.org/clinical-guidance/gastrointestinal-evaluation-of-iron-deficiency-anemia' },
  devalia2014: { t: 'BSH Cobalamin & folate 2014', c: 'Devalia V, et al. Guidelines for the diagnosis and treatment of cobalamin and folate disorders. Br J Haematol 2014;166(4):496–513.', u: pm('Guidelines for the diagnosis and treatment of cobalamin and folate disorders Devalia') },
  acc_bleed2020: { t: 'ACC 2020 — Bleeding on oral anticoagulants', c: 'Tomaselli GF, et al. 2020 ACC Expert Consensus Decision Pathway on Management of Bleeding in Patients on Oral Anticoagulants. J Am Coll Cardiol 2020;76(5):594–622.', u: pm('2020 ACC Expert Consensus Decision Pathway on Management of Bleeding in Patients on Oral Anticoagulants') },
  acg_ugib2021: { t: 'ACG Upper GI bleeding 2021', c: 'Laine L, et al. ACG Clinical Guideline: Upper Gastrointestinal and Ulcer Bleeding. Am J Gastroenterol 2021;116(5):899–917.', u: pm('ACG Clinical Guideline: Upper Gastrointestinal and Ulcer Bleeding 2021') },
  merck_hemat: { t: 'Merck Manual Professional — Anemia', c: 'Merck Manual Professional Version. Evaluation of Anemia; Overview of Hemolytic Anemia.', u: 'https://www.merckmanuals.com/professional/hematology-and-oncology/approach-to-the-patient-with-anemia/evaluation-of-anemia' },
  // pain, surgery, palliative
  cdc_opioid2022: { t: 'CDC Opioid Guideline 2022', c: 'Dowell D, et al. CDC Clinical Practice Guideline for Prescribing Opioids for Pain — United States, 2022. MMWR Recomm Rep 2022;71(3):1–95.', u: 'https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm' },
  boast_cs: { t: 'BOAST — Compartment syndrome', c: 'British Orthopaedic Association Standards for Trauma (BOAST): Diagnosis and management of compartment syndrome of the limbs.', u: 'https://www.boa.ac.uk/standards-guidance/boasts.html' },
  wses_asbo: { t: 'WSES Bologna guidelines — ASBO', c: 'ten Broek RPG, et al. Bologna guidelines for diagnosis and management of adhesive small bowel obstruction (ASBO): 2017 update. World J Emerg Surg 2018;13:24.', u: pm('Bologna guidelines for diagnosis and management of adhesive small bowel obstruction 2017 update') },
  asco_dyspnea2021: { t: 'ASCO Dyspnea in advanced cancer 2021', c: 'Hui D, et al. Management of Dyspnea in Advanced Cancer: ASCO Guideline. J Clin Oncol 2021;39(12):1389–1411.', u: pm('Management of Dyspnea in Advanced Cancer: ASCO Guideline') },
  merck_labs: { t: 'Merck Manual — Normal laboratory values', c: 'Merck Manual Professional Version. Normal Laboratory Values (reference ranges vary by laboratory).', u: 'https://www.merckmanuals.com/professional/resources/normal-laboratory-values' },
  // pedagogy
  tanner2006: { t: 'Tanner Clinical Judgment Model (2006)', c: 'Tanner CA. Thinking like a nurse: a research-based model of clinical judgment in nursing. J Nurs Educ 2006;45(6):204–211.', u: pm('Thinking like a nurse: a research-based model of clinical judgment in nursing') },
  lasater2007: { t: 'Lasater Clinical Judgment Rubric (2007)', c: 'Lasater K. Clinical judgment development: using simulation to create an assessment rubric. J Nurs Educ 2007;46(11):496–503.', u: pm('Clinical judgment development: using simulation to create an assessment rubric') },
  ncjmm2019: { t: 'NCSBN Clinical Judgment Measurement Model', c: 'Dickison P, Haerling KA, Lasater K. Integrating the National Council of State Boards of Nursing Clinical Judgment Model into nursing educational frameworks. J Nurs Educ 2019;58(2):72–78.', u: pm('Integrating the National Council of State Boards of Nursing Clinical Judgment Model into Nursing Educational Frameworks') },
  roediger2006: { t: 'Retrieval practice (2006)', c: 'Roediger HL, Karpicke JD. Test-enhanced learning: taking memory tests improves long-term retention. Psychol Sci 2006;17(3):249–255.', u: pm('Test-enhanced learning: taking memory tests improves long-term retention') },
  cepeda2006: { t: 'Spacing effect meta-analysis (2006)', c: 'Cepeda NJ, et al. Distributed practice in verbal recall tasks: a review and quantitative synthesis. Psychol Bull 2006;132(3):354–380.', u: pm('Distributed practice in verbal recall tasks: a review and quantitative synthesis') },
  hattie2007: { t: 'The power of feedback (2007)', c: 'Hattie J, Timperley H. The power of feedback. Rev Educ Res 2007;77(1):81–112.', u: 'https://doi.org/10.3102/003465430298487' },
  berner2008: { t: 'Overconfidence & diagnostic error (2008)', c: 'Berner ES, Graber ML. Overconfidence as a cause of diagnostic error in medicine. Am J Med 2008;121(5 Suppl):S2–S23.', u: pm('Overconfidence as a cause of diagnostic error in medicine') },
  kononowicz2019: { t: 'Virtual patients meta-analysis (2019)', c: 'Kononowicz AA, et al. Virtual patient simulations in health professions education: systematic review and meta-analysis by the Digital Health Education Collaboration. J Med Internet Res 2019;21(7):e14676.', u: pm('Virtual Patient Simulations in Health Professions Education: Systematic Review and Meta-Analysis') },
  gentry2019: { t: 'Serious games in health education (2019)', c: 'Gentry SV, et al. Serious gaming and gamification education in health professions: systematic review. J Med Internet Res 2019;21(3):e12994.', u: pm('Serious Gaming and Gamification Education in Health Professions: Systematic Review') },
  muller2018: { t: 'SBAR systematic review (2018)', c: 'Müller M, et al. Impact of the communication and patient hand-off tool SBAR on patient safety: a systematic review. BMJ Open 2018;8:e022202.', u: pm('Impact of the communication and patient hand-off tool SBAR on patient safety: a systematic review') },
};

/* Episode → sources + one concrete, guideline-derived key point. */
const EP_EVIDENCE = {
  'orthostasis': { s: ['freeman2011', 'beers2023', 'falls2022'], k: 'הגדרה: ירידה של ≥20 mmHg סיסטולי או ≥10 דיאסטולי תוך 3 דקות עמידה. חוסמי α-1 (כמו doxazosin) מופיעים ב-Beers 2023 כ“להימנע” לטיפול ביתר לחץ דם בגלל סיכון לאורתוסטזיס ונפילות.' },
  'iron': { s: ['aga2020', 'merck_hemat'], k: 'AGA 2020: ferritin <45 ng/mL תומך בחסר ברזל (רגישות 85%, סגוליות 92%). בגברים ובנשים אחרי גיל המעבר — מומלץ בירור מקור במערכת העיכול (אנדוסקופיה דו-כיוונית), לא רק תוסף.' },
  'retention-delirium': { s: ['tieges2021', 'nice_delirium', 'beers2023'], k: 'סקר דליריום בכלי מתוקף כמו 4AT (רגישות וסגוליות ~88%). Beers 2023: להימנע מתרופות אנטיכולינרגיות חזקות במבוגרים; NICE: קודם מחפשים ומטפלים בגורם (אצירה, עצירות, כאב, תרופות) — לא סדציה.' },
  'creatinine': { s: ['beers2023', 'kdigo_ckd2024'], k: 'התאמת מינון נעשית לרוב לפי פינוי קריאטינין (Cockcroft-Gault). Beers 2023 כולל טבלת התאמה כלייתית — גם ל-gabapentinoids (pregabalin), שהצטברותם גורמת לסדציה, אטקסיה ונפילות.' },
  'stroke': { s: ['aha_stroke2019'], k: 'AHA/ASA 2019: thrombolysis (alteplase) עד 4.5 שעות מ-Last Known Well במטופלים מתאימים; thrombectomy לחסימת כלי גדול עד 24 שעות בנבחרים. בדיקת גלוקוז לפני החלטה — כי היפוגליקמיה מחקה שבץ.' },
  'seizure-postictal': { s: ['trinka2015'], k: 'ILAE 2015: פרכוס טוני-קלוני מעל 5 דקות הוא status epilepticus. כשההכרה לא חוזרת כצפוי — NCSE היא אבחנה שדורשת EEG; אי אפשר לשלול אותה ליד המיטה.' },
  'dysphagia': { s: ['aha_stroke2019'], k: 'AHA/ASA 2019: סקר בליעה לפני כל אכילה, שתייה או תרופה פומית אחרי שבץ; קול רטוב ושיעול אחרי לגימה הם סימני אספירציה. הערכה מלאה על ידי קלינאי/ת תקשורת לפי הצורך.' },
  'copd': { s: ['bts_o2_2017', 'gold2025'], k: 'BTS: ביעד SpO₂ של 88–92% במטופלים בסיכון ל-hypercapnia (חמצן “ללא יעד” מחמיר אותה). GOLD: NIV בהחמרת COPD עם pH ≤7.35 ו-PaCO₂ ≥45 mmHg.' },
  'unstable-af': { s: ['acls2020', 'af2023'], k: 'AHA 2020: טכיאריתמיה עם סימני אי-יציבות (hypotension, שינוי הכרה, כאב איסכמי, אי-ספיקת לב חריפה) → synchronized cardioversion מיידי. קודם “יציב או לא?”, אחר כך “כמה דופק?”.' },
  'hf-congestion': { s: ['hf2022', 'beers2023'], k: 'AHA/ACC/HFSA 2022: NSAIDs מחמירים אי-ספיקת לב ויש להימנע מהם; עלייה מהירה במשקל + orthopnea הם סימני גודש. Beers 2023: להימנע מ-NSAIDs ב-HF.' },
  'aspiration-pneumonia': { s: ['mandell2019', 'aha_stroke2019'], k: 'אספירציה היא סיבוך שכיח של דיספגיה במבוגרים (Mandell & Niederman 2019). המניעה היא תפקודית: מרקם מותאם, תנוחה, פיקוח בזמן ארוחה והערכת בליעה חוזרת.' },
  'hyperk': { s: ['ukka_k'], k: 'UKKA: עם שינויי ECG — calcium IV להגנה על הממברנה מיד; insulin-glucose להעברת K לתאים (עם ניטור גלוקוז בגלל היפוגליקמיה); אחר כך סילוק ובדיקה חוזרת.' },
  'hypona': { s: ['spasovski2014', 'beers2023'], k: 'הנחיה אירופית 2014: בהיפונתרמיה כרונית — תיקון של עד 10 mmol/L ב-24 השעות הראשונות ועד 8 בכל יממה נוספת (סיכון ל-osmotic demyelination). תסמינים קשים: 3% saline 150 mL בבולוס. Thiazide ו-SSRI הם גורמים שכיחים (Beers).' },
  'hypoglycemia': { s: ['ada2025'], k: 'ADA 2025: יעד A1c <7.0–7.5% במבוגר בריא יחסית ו-<8.0% במורכבות/שבריריות; אחרי היפוגליקמיה — deintensification והימנעות מ-sulfonylureas ואינסולין אינטנסיבי כשאפשר.' },
  'hhs': { s: ['umpierrez2024'], k: 'Consensus 2024: HHS — גלוקוז ≥600 mg/dL, אוסמולריות אפקטיבית >300 ללא חמצת משמעותית. נוזלים הם הצעד הראשון; מטרה היא ירידה הדרגתית באוסמולריות ובנתרן.' },
  'sepsis': { s: ['ssc2021', 'sepsis3'], k: 'Surviving Sepsis 2021: אנטיביוטיקה תוך שעה כשיש shock או sepsis סביר; 30 mL/kg קריסטלואידים בהיפופרפוזיה; יעד MAP ≥65; לקטט ≥4 הוא סימן אזהרה. Sepsis-3 מגדיר sepsis דרך פגיעה תפקודית באיברים — לא דרך WBC.' },
  'dic': { s: ['taylor2001'], k: 'ניקוד ISTH ל-DIC: טסיות, D-dimer, PT ו-fibrinogen; ניקוד ≥5 מתאים ל-overt DIC. הטיפול הוא בגורם, ומוצרי דם לפי דימום והקשר — לא לפי “תיקון מספרים”.' },
  'occult-bleed': { s: ['acc_bleed2020', 'beers2023'], k: 'ACC 2020: בדימום על נוגד קרישה — לדרג חומרה (המודינמיקה, ירידת Hb ≥2 g/dL, אתר קריטי), להפסיק את התרופה ולשקול reversal לפי חומרה. NSAID + נוגד קרישה מעלה סיכון לדימום (Beers).' },
  'head': { s: ['nice_ng232'], k: 'NICE NG232: גם ללא סימנים אחרים — במטופל על נוגד קרישה לשקול CT ראש תוך 8 שעות מהחבלה. ירידה ב-GCS או כאב ראש מחמיר הם אינדיקציה ל-CT דחוף.' },
  'gi-bleed': { s: ['acg_ugib2021', 'aabb2023'], k: 'ACG 2021: ריבוד סיכון (Glasgow-Blatchford), אנדוסקופיה תוך 24 שעות ועירוי לפי סף מגביל (AABB 2023: לרוב Hb <7, ובמחלה קרדיווסקולרית <8 g/dL).' },
  'opioid': { s: ['cdc_opioid2022', 'beers2023'], k: 'CDC 2022: להימנע משילוב opioid + benzodiazepine; בדיכוי נשימתי — naloxone. משך פעולתו קצר משל רוב ה-opioids, ולכן חובה ניטור לחזרת הדיכוי.' },
  'grand': { s: ['stopp2023', 'beers2023', 'scott2015'], k: 'STOPP/START v3 ו-Beers 2023 מזהים מרשמים לא מתאימים; תהליך deprescribing מובנה (Scott 2015): רשימה מלאה, סיכון מול תועלת, time-to-benefit, הפסקה הדרגתית אחת-אחת ומעקב.' },
  'troponin': { s: ['thygesen2018'], k: 'ההגדרה האוניברסלית הרביעית: troponin מעל אחוזון 99 = myocardial injury. אבחנת MI דורשת עלייה/ירידה ועדות לאיסכמיה; ב-sepsis ו-CKD שכיח injury שאינו MI מסוג 1.' },
  'discharge': { s: ['nice_ng27', 'ahrq_teachback'], k: 'NICE NG27: תכנון שחרור מתחיל בקבלה, כולל הערכת תפקוד, ביתר ומטפלים. Teach-back (AHRQ) בודק הבנה בפועל — לא חתימה על דף.' },
  'b12-neuro': { s: ['devalia2014'], k: 'BSH 2014: חסר B12 עם תסמינים נוירולוגיים — לטפל מיד ב-hydroxocobalamin IM בלי להמתין לבירור המלא. metformin ו-PPI לאורך זמן מורידים B12.' },
  'hypoactive-delirium': { s: ['nice_delirium', 'tieges2021', 'inouye1999'], k: 'דליריום היפואקטיבי הוא הצורה השכיחה בזקנים, והקשה ביותר לזהות. סקר שגרתי (4AT) ותוכנית רב-מרכיבית (HELP) מורידים שכיחות דליריום.' },
  'pe-suspicion': { s: ['esc_pe2019', 'righini2014'], k: 'ESC 2019: הסתברות קלינית (Wells/Geneva) קודם לבדיקות. מעל גיל 50 — D-dimer מותאם גיל (גיל × 10 µg/L) מגדיל את מספר המבוגרים שאפשר לשלול אצלם PE בבטחה (ADJUST-PE).' },
  'digoxin-brady': { s: ['af2023', 'beers2023'], k: 'Digoxin מופרש בכליה: AKI מעלה רמות ו-toxicity (בחילה, בלבול, ברדיקרדיה). Beers 2023: להימנע ממינון >0.125 mg/d. בטוקסיות משמעותית — נוגדן ספציפי (digoxin immune Fab).' },
  'mixed-acidbase': { s: ['berend2014'], k: 'נוסחת Winter: PaCO₂ צפוי = 1.5×HCO₃ + 8 (±2). כאן: 1.5×15+8 ≈ 30.5. PaCO₂ 25 נמוך מהצפוי → יש גם respiratory alkalosis. pH “תקין” מסתיר שתי הפרעות.' },
  'hypernatremia': { s: ['adrogue2000'], k: 'בהיפרנתרמיה כרונית — ירידה של עד ~10 mmol/L ביממה כדי למנוע בצקת מוחית. במבוגר תלוי, הסיבה היא לרוב גישה למים — לכן זו גם בעיה של תכנית הטיפול.' },
  'renal-antibiotic': { s: ['kdigo_aki2012'], k: 'KDIGO: AKI = עלייה ב-Cr של ≥0.3 mg/dL תוך 48 שעות, או ≥1.5× מה-baseline תוך 7 ימים, או שתן <0.5 mL/kg/h במשך 6 שעות. AKI מחייב בדיקה מחודשת של כל מינון.' },
  'opioid-ileus': { s: ['cdc_opioid2022', 'wses_asbo'], k: 'עצירות מ-opioids צפויה — מתחילים משלשל מניעתי עם תחילת הטיפול. כאב מתגבר, הקאות והיעדר גזים מחייבים להעריך ileus/חסימה לפני “עוד משלשל”.' },
  'goals-hf': { s: ['hf2022'], k: 'AHA/ACC/HFSA 2022: שילוב טיפול פליאטיבי ושיחה על מטרות בכל HF מתקדם — לצד טיפול במחלה, לא במקומו. מטרות המטופלת מכוונות את התכנית.' },
  'qt-stack': { s: ['drew2010'], k: 'AHA 2010: QTc >500 ms או עלייה של >60 ms = סיכון גבוה ל-torsades. להפסיק תרופות מאריכות QT, לשמור K ≥4 ו-Mg ≥2, ולנטר ECG.' },
  'pressure-injury': { s: ['npiap2019'], k: 'NPIAP/EPUAP 2019: אודם שאינו מחוויר בלחיצה = פגיעת לחץ דרגה 1. לא לעסות את האזור; שינויי תנוחה, משטח מפחית לחץ, הערכת עור ותזונה.' },
  'symptomatic-brady': { s: ['acls2020'], k: 'AHA 2020: ברדיקרדיה סימפטומטית — atropine 1 mg IV (חוזר כל 3–5 דקות עד 3 mg); אם אינו יעיל: קיצוב חיצוני או עירוי dopamine/epinephrine, ובמקביל חיפוש גורם הפיך (תרופות, K).' },
  'pulmonary-edema': { s: ['hf2022'], k: 'AHA/ACC/HFSA 2022: בגודש — משתן לולאה IV והערכה חוזרת של תסמינים, משקל, תפוקת שתן ותפקוד כליה; בבצקת ריאות עם מצוקה — לשקול NIV.' },
  'refeeding': { s: ['nice_cg32'], k: 'NICE CG32: בסיכון גבוה ל-refeeding — להתחיל עד 10 kcal/kg/day ולהעלות בהדרגה, לתת thiamine לפני ובמהלך ההזנה, ולנטר ולתקן phosphate, K ו-Mg.' },
  'dka-sglt2': { s: ['umpierrez2024'], k: 'Consensus 2024: הסף לגלוקוז ב-DKA ירד ל-≥200 mg/dL, או כל ערך בסוכרת ידועה, בגלל euglycemic DKA תחת SGLT2. אבחנה לפי ketones + חמצת (pH <7.3 או HCO₃ <18).' },
  'hypercalcemia': { s: ['endo_ca2023'], k: 'Endocrine Society 2023: היפרקלצמיה סימפטומטית/חמורה — נוזלים IV ואחר כך bisphosphonate (או denosumab באי-ספיקת כליה). בבירור תמיד בודקים את הצמד PTH + calcium.' },
  'cdiff': { s: ['idsa_cdi2021'], k: 'IDSA/SHEA 2021: fidaxomicin מועדף (vancomycin פומי — חלופה); חומרה: WBC ≥15,000 או Cr >1.5 mg/dL. בידוד מגע ורחיצת ידיים במים וסבון — אלכוהול לא הורג נבגים.' },
  'neutropenic-fever': { s: ['freifeld2011'], k: 'IDSA: חום (≥38.3 פעם אחת או ≥38.0 לאורך שעה) עם ANC <500 = מצב דחוף. תרביות ואנטיביוטיקה רחבה ללא דיחוי — היעד הוא תוך שעה.' },
  'transfusion-reaction': { s: ['bsh_atr2023'], k: 'BSH 2023: בכל תסמין חדש בזמן עירוי — לעצור מיד, לשמור על הוריד, להעריך ABC, לבדוק התאמת זיהוי מטופל/מוצר, לדווח ולשמור את השקית לבירור.' },
  'line-sepsis': { s: ['mermel2009'], k: 'IDSA: בחשד לזיהום קו — תרביות מהקו ומדקירה פריפרית; בבקטרמיה ממקור הקו לרוב מוציאים את הקו. כל יום עונים מחדש: האם הקו עדיין נחוץ?' },
  'compartment': { s: ['boast_cs'], k: 'BOAST: כאב לא פרופורציונלי וכאב במתיחה פסיבית הם סימנים מוקדמים; דופק נשמר עד שלב מאוחר. הערכה דחופה של אורתופד וכריתת פאסיה כשנדרש — לא להמתין להיעלמות הדופק.' },
  'hip-delirium': { s: ['nice_cg124', 'nice_delirium'], k: 'NICE CG124: הערכה קוגניטיבית בקבלה, משככי כאבים יעילים (כולל חסם עצבי), ניתוח ביום הקבלה או למחרת, ומוביליזציה כבר ביום שאחרי הניתוח.' },
  'palliative-dyspnea': { s: ['asco_dyspnea2021'], k: 'ASCO 2021: קוצר נשימה בסרטן מתקדם — לטפל בגורמים הפיכים לפי המטרות, להשתמש באמצעים לא-תרופתיים (כמו מאוורר לפנים) ו-opioids סיסטמיים להקלה. SpO₂ אינו מטרת הטיפול.' },
  'bowel-obstruction': { s: ['wses_asbo'], k: 'WSES: חשד לחסימה — CT כבדיקת הדמיה מועדפת, NPO, נוזלים וניקוז בזונדה לפי הצורך. סימני איסכמיה או פריטוניטיס → ניתוח דחוף.' },
  'med-reconciliation': { s: ['who_toc2019', 'ahrq_teachback'], k: 'WHO 2019: מעברי טיפול הם נקודת הסיכון העיקרית לטעויות תרופתיות. התאמה מול כל מקור (Best Possible Medication History) ורשימה אחת מוסברת + Teach-back.' },
  'caregiver-capacity': { s: ['ahrq_teachback', 'nice_ng27'], k: 'Teach-back והדגמה חוזרת (show-me) מאמתים שהמטפל/ת יכול/ה לבצע העברות, האכלה ומתן תרופות. NICE NG27 כולל את המטפלים בתכנון השחרור.' },
  'mixed-anemia-v21': { s: ['aga2020', 'devalia2014'], k: 'MCV הוא ממוצע: חסר ברזל (מיקרוציטים) + חסר B12 (מקרוציטים) יכולים לתת MCV תקין עם RDW גבוה. ferritin <45 תומך בחסר ברזל; B12 נמוך עם נוירופתיה — טיפול מיידי.' },
  'ckd-iron-v21': { s: ['kdigo_anemia2026'], k: 'KDIGO: מעריכים מצב ברזל ב-CKD לפי ferritin ו-TSAT יחד. ferritin “תקין” בזמן דלקת לא שולל חסר ברזל תפקודי (TSAT נמוך).' },
  'overdiuresis-v21': { s: ['hf2022', 'freeman2011'], k: 'ירידה במשקל עם אורתוסטזיס, עליית Cr ו-K/Mg נמוכים = טיפול-יתר במשתן. HF 2022: להתאים את מינון המשתן למצב הנוזלים לאורך הזמן.' },
  'raas-nsaid-v21': { s: ['kdigo_aki2012', 'ukka_k', 'beers2023'], k: 'ACEi/ARB + MRA + NSAID במצב של התייבשות הוא שילוב מוכר שגורם ל-AKI והיפרקלמיה. Beers 2023 מזהיר מפני NSAIDs ב-CKD.' },
  'brady-stack-v21': { s: ['acls2020', 'af2023'], k: 'חוסם β + digoxin + AKI = הצטברות והאטה ב-AV node. ACLS: הערכת יציבות קודם; במקביל עוצרים את התרופות המאטות ובודקים K ותפקוד כליה.' },
  'amlodipine-edema-v21': { s: ['esc_htn2024', 'hf2022'], k: 'בצקת היקפית תלוית מינון היא תופעת לוואי שכיחה של חוסמי סידן דיהידרופירידיניים, בלי גודש מערכתי. לפני משתן — לבדוק ריאות, JVP, משקל ו-orthopnea.' },
  'acute-bloodloss-v21': { s: ['acc_bleed2020', 'acg_ugib2021'], k: 'בדימום חריף Hb ו-MCV עוד לא משקפים את האובדן; ה-trend וההמודינמיקה קובעים את הדחיפות. דימום על נוגד קרישה — לדרג חומרה ולשקול reversal.' },
  'hemolysis-v21': { s: ['merck_hemat'], k: 'דפוס המוליזה: retic גבוה + LDH ובילירובין לא-ישיר גבוהים + haptoglobin נמוך. השלב הבא: משטח דם ו-DAT (Coombs) כדי להבחין בין המוליזה חיסונית ללא-חיסונית.' },
};

const LAB_ROUND_SOURCES = [['aga2020', 'devalia2014'], ['kdigo_anemia2026'], ['merck_hemat'], ['hf2022', 'freeman2011'], ['ukka_k', 'kdigo_aki2012'], ['acls2020', 'af2023'], ['esc_htn2024'], ['spasovski2014'], ['aabb2023', 'acc_bleed2020'], ['thygesen2018'], ['berend2014', 'ssc2021'], ['acc_bleed2020', 'aga2020']];
const EVENT_SOURCES = [['aga2020'], ['kdigo_aki2012', 'ukka_k'], ['freeman2011', 'beers2023'], ['aha_stroke2019'], ['bts_o2_2017', 'gold2025'], ['ukka_k'], ['ssc2021', 'sepsis3'], ['nice_ng232'], ['stopp2023', 'beers2023'], ['beers2023', 'kdigo_ckd2024']];
const LAB_SOURCES = { ferritin: ['aga2020'], tsat: ['kdigo_anemia2026'], b12: ['devalia2014'], folate: ['devalia2014'], ddimer: ['righini2014'], troponin: ['thygesen2018'], egfr: ['kdigo_ckd2024'], creat: ['kdigo_aki2012'], hba1c: ['ada2025'], glucose: ['ada2025'], na: ['spasovski2014'], k: ['ukka_k'], lactate: ['ssc2021'], hb: ['aabb2023'], fibrinogen: ['taylor2001'], ph: ['berend2014'], paco2: ['berend2014'], hco3abg: ['berend2014'], aniongap: ['berend2014'], phos: ['nice_cg32'], ca: ['endo_ca2023'], pth: ['endo_ca2023'] };
/* Reference-range corrections to the legacy lab table. */
const LAB_FIXES = { b12: { range: '~200–900 (200–300 = גבולי)' }, neut: { range: '40–70' } };

/* Why the game works the way it does. */
const PEDAGOGY = [
  { icon: '🔍🧠💉📋', t: 'ארבעת השלבים של שיפוט קליני', g: 'אומדן → פרשנות → מטרה/התערבות → הערכה חוזרת', why: 'המודל של Tanner (Noticing, Interpreting, Responding, Reflecting) הוא הבסיס לרובריקת Lasater ולמודל המדידה של NCSBN. כל קרב בנוי לפיו, וכרטיס האח/ות מודד כל שלב בנפרד.', s: ['tanner2006', 'lasater2007', 'ncjmm2019'] },
  { icon: '🛏️', t: 'מטופלים וירטואליים ותרחישים', g: '58 אירועים אצל 7 מטופלים שחוזרים לאורך המשחק', why: 'מטה-אנליזות מראות שסימולציות של מטופלים וירטואליים משפרות מיומנויות ושיפוט קליני לפחות כמו הוראה מסורתית, ומשחקים רציניים משפרים ידע כשהמכניקה צמודה למטרת הלמידה.', s: ['kononowicz2019', 'gentry2019'] },
  { icon: '✓✗', t: 'משוב מיידי ומוסבר', g: 'כל טעות מקבלת רמז, וכל אירוע נגמר בסיכום: תשובות, ממצאים, פנינה וסיכון', why: 'משוב ממוקד-משימה שמסביר “איפה אני, לאן הולכים ואיך” הוא מהמשתנים בעלי ההשפעה הגדולה ביותר על למידה.', s: ['hattie2007'] },
  { icon: '😎', t: 'כיול ביטחון', g: 'בוחרים ניחוש/סביר/בטוח לפני כל החלטה; ביטחון-יתר עולה יותר', why: 'ביטחון-יתר הוא גורם מרכזי לטעויות אבחנה. אימון לזהות “מתי אני בטוח ולא צודק” משפר את ההחלטות.', s: ['berner2008'] },
  { icon: '📟', t: 'שליפה מרווחת', g: 'קריאות ביפר, מתמחים וסימולציות חוזרות מחזירים חומר שכבר נלמד', why: 'מבחן (שליפה) עדיף על קריאה חוזרת לזכירה ארוכת טווח, וחזרה מרווחת בזמן חזקה מחזרה מרוכזת.', s: ['roediger2006', 'cepeda2006'] },
  { icon: '📝', t: 'מסירה ב-SBAR', g: 'כל אירוע נסגר במסירה מובנית', why: 'כלי מסירה מובנה כמו SBAR משפר תקשורת ובטיחות מטופלים.', s: ['muller2018'] },
];

function srcLinks(ids, cls) {
  return (ids || []).filter(id => SOURCES[id]).map(id => `<a class="src ${cls || ''}" href="${SOURCES[id].u}" target="_blank" rel="noopener" title="${esc(SOURCES[id].c)}">${esc(SOURCES[id].t)}</a>`).join('');
}
function srcFull(ids) { return (ids || []).filter(id => SOURCES[id]).map(id => `<li><a href="${SOURCES[id].u}" target="_blank" rel="noopener">${esc(SOURCES[id].c)}</a></li>`).join(''); }

// apply reference-range fixes to the content
(C.labs || []).forEach(l => { if (LAB_FIXES[l.id]) Object.assign(l, LAB_FIXES[l.id]); });
